config/routes.rb
Rails.application.routes.draw do
  resource :strips, only: :show, :defaults => { :format => :atom } do
    get '/latest' => 'strips#show', :defaults => { :latest => true }, :path => 'latest'
  end
  root 'site#index'
end

app/models/strip.rb
class Strip
  include Mongoid::Document
  include Mongoid::Timestamps::Updated

  field :number, type: Integer
  field :image, type: String
  field :header, type: String
  field :previous, type: Integer

  index({ number: 1 }, unique: true)

  validates_presence_of :number, :image, :previous
  validates_uniqueness_of :number, :previous

  def self.latest
    number = Rails.cache.fetch('strip#latest') do
      Rails.logger.info 'Strip#latest - cache miss'
      max(:number)
    end

    find_by(number: number)
  end

  def title
    "Tirinha número #{number}"
  end

  def url
    "http://www.malvados.com.br/index#{number}.#{extension}"
  end

  def content
    %Q{
      <p>
        <img src="#{header}" alt="#{title}" />
      </p>
      <p>
        <a href="#{url}">
          <img src="#{image}" alt="#{title}" />
        </a>
      </p>
    }
  end

  private

  def extension
    number == 123 ? 'htm' : 'html'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def append_info_to_payload(payload)
    super
    payload[:uuid] = env['action_dispatch.request_id']
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @title = 'Malvados Feed - Tirinhas dos Malvados'
    @latest = Strip.latest
    @count = Strip.count
  end
end

app/controllers/strips_controller.rb
class StripsController < ApplicationController
  def show
    expires_in 1.hour, public: true

    @settings = StripBuilder.new.settings
    @latest = Strip.latest

    @strips = if params.has_key?(:latest)
      [ @latest ]
    else
      Strip.order_by(number: :desc)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="chrome=1">
  <title><%= @title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <%= auto_discovery_link_tag :atom, strips_url(:atom), title: @title %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <!--[if lt IE 9]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>Malvados Feed</h1>
    <p>Yet Another Malvados Feed</p>
  </header>

  <div id="banner">
    <div class="banner-inner">
      <span id="logo"></span>

      <a href="https://github.com/danilopopeye/malvados-feed" class="button fork"><strong>Fork On GitHub</strong></a>

      <div class="downloads">
        <span>Feed:</span>

        <ul>
          <li><%= link_to 'Latest', latest_strips_path, :class => 'button' %></li>
          <li><%= link_to 'All', strips_path, :class => 'button' %></li>
        </ul>
      </div>
    </div>
  </div><!-- end banner -->

  <div class="wrapper">
    <nav>
      <ul></ul>
    </nav>

    <section>
      <%= yield %>
    </section>

    <footer>
      <p>Project maintained by <a href="https://github.com/danilopopeye">danilopopeye</a></p>
      <p><span class="small">Hosted on Heroku &mdash; Theme by <a href="http://twitter.com/#!/michigangraham">mattgraham</a></span></p>
    </footer>
  </div>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  <%= javascript_include_tag 'application' %>
  <!--[if !IE]><script>fixScale(document);</script><![endif]-->
</body>
</html>

app/views/site/index.html.erb
<h2>Feed statistics</h2>
<p>Strips: <b><%= @count %></b></p>
<p>Latest update: (<%= @latest.number %>) <b><%= @latest.updated_at %></b></p>